### ISSUE TITLE
how to get the test_labels.csv in your project？

### ISSUE THREAD

**Issue by vitamin-github** [IraKorshunova/kaggle-seizure-prediction#1]
There is an error that  IOError: File ...**/kaggle_data/test_labels.csv** does not exist When i run your code .Can you explain how to generate the file **test_labels.csv**?

**Comment by vitamin-github** [comment]
There is an error that IOError: File .../kaggle_data/test_labels.csv does not exist When i run your code .Can you explain how to generate the file test_labels.csv? 
Thanks a lot.

**Comment by IraKorshunova** [comment]
I can't remember for sure, but I think this is the file shared here: https://www.kaggle.com/c/seizure-prediction/discussion/10955#82009

**Comment by vitamin-github** [comment]
Thank you




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            闵腾飞
                            
                            
                                
                                    邮箱：vitaminmtffly@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 05/13/2018 04:29, IraKorshunova wrote: I can't remember for sure, but I think this is the file shared here: https://www.kaggle.com/c/seizure-prediction/discussion/10955#82009

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IraKorshunova/kaggle-seizure-prediction","title":"IraKorshunova/kaggle-seizure-prediction","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/IraKorshunova/kaggle-seizure-prediction"}},"updates":{"snippets":[{"icon":"PERSON","message":"@IraKorshunova in #1: I can't remember for sure, but I think this is the file shared here: https://www.kaggle.com/c/seizure-prediction/discussion/10955#82009 "}],"action":{"name":"View Issue","url":"https://github.com/IraKorshunova/kaggle-seizure-prediction/issues/1#issuecomment-388580922"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [IraKorshunova/kaggle-seizure-prediction] how to get the test_labels.csv in your project？ (#1)","sections":[{"text":"","activityTitle":"**IraKorshunova**","activityImage":"https://avatars3.githubusercontent.com/u/3956298?s=160\u0026v=4","activitySubtitle":"@IraKorshunova","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"IraKorshunova/kaggle-seizure-prediction\",\"issueId\":1,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"IraKorshunova/kaggle-seizure-prediction\",\"issueId\":1}"},{"targets":[{"os":"default","uri":"https://github.com/IraKorshunova/kaggle-seizure-prediction/issues/1#issuecomment-388580922"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":334562929}"}],"themeColor":"26292E"}
