### ISSUE TITLE
Some problems with running train.py

### ISSUE THREAD

**Issue by wangyue663** [IraKorshunova/kaggle-seizure-prediction#2]
Hello, I reported several errors when running train.py in the code of kaggle-seizure-prediction-master, such as WindowsError: [Error 5] Error in atexit._run_exitfuncs:, WindowsError: [Error 5]
Error in sys.exitfunc:, do you know what's going on? Can you tell me the version of the library you are using? thank you very much.

**Comment by wangyue663** [comment]
I solved the last problem. I have another question, that is, the size of x.shape is (2772, 16, 9, 20), why add a standard deviation to 9 on the basis of 8 frequency bands?

**Comment by IraKorshunova** [comment]
Hello! I'm sorry, I wrote this code a very long ago and I don't remember why that is. If it seems weird, maybe it was a bug.

**Comment by wangyue663** [comment]
I am very glad that you replied to me. I will check the information and think about it by myself. I believe I will figure it out.
